### ISSUE TITLE
support safari ? need to change call system('x5050 Safari'.shellescape(a:url))

### ISSUE THREAD

**Issue by hawkinchina** [junegunn/x5050#1]
if has('mac') && excutable('x5050')
  function! MKDPSplit(url)
    call system('x5050 '.shellescape(a:url))
  endfunction

  let g:mkdp_browserfunc = 'MKDPSplit'
endif

**Comment by hawkinchina** [comment]
call system('x5050 Safari '.shellescape(a:url))  ,this is ok. thanks

**Comment by junegunn** [comment]
Note that `excutable` was a typo. It should be `executable`.
